=== struqt/struqt-jdbc/struqt-jdbc-config/src/main/resources/invar/data/data.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns:tns="invar.data" targetNamespace="invar.data">

<xs:element name="root" type="tns:com.struqt.jdbc.config.JdbcRunnerConf" />

<xs:complexType name="int8"><xs:simpleContent><xs:extension base="xs:string">
  <xs:attribute type="xs:byte" name="value" use="optional"/></xs:extension></xs:simpleContent></xs:complexType>
<xs:complexType name="int16"><xs:simpleContent><xs:extension base="xs:string">
  <xs:attribute type="xs:short" name="value" use="optional"/></xs:extension></xs:simpleContent></xs:complexType>
<xs:complexType name="int32"><xs:simpleContent><xs:extension base="xs:string">
  <xs:attribute type="xs:int" name="value" use="optional"/></xs:extension></xs:simpleContent></xs:complexType>
<xs:complexType name="int64"><xs:simpleContent><xs:extension base="xs:string">
  <xs:attribute type="xs:long" name="value" use="optional"/></xs:extension></xs:simpleContent></xs:complexType>
<xs:complexType name="uint8"><xs:simpleContent><xs:extension base="xs:string">
  <xs:attribute type="xs:unsignedByte" name="value" use="optional"/></xs:extension></xs:simpleContent></xs:complexType>
<xs:complexType name="uint16"><xs:simpleContent><xs:extension base="xs:string">
  <xs:attribute type="xs:unsignedShort" name="value" use="optional"/></xs:extension></xs:simpleContent></xs:complexType>
<xs:complexType name="uint32"><xs:simpleContent><xs:extension base="xs:string">
  <xs:attribute type="xs:unsignedInt" name="value" use="optional"/></xs:extension></xs:simpleContent></xs:complexType>
<xs:complexType name="uint64"><xs:simpleContent><xs:extension base="xs:string">
  <xs:attribute type="xs:unsignedLong" name="value" use="optional"/></xs:extension></xs:simpleContent></xs:complexType>
<xs:complexType name="float"><xs:simpleContent><xs:extension base="xs:string">
  <xs:attribute type="xs:float" name="value" use="optional"/></xs:extension></xs:simpleContent></xs:complexType>
<xs:complexType name="double"><xs:simpleContent><xs:extension base="xs:string">
  <xs:attribute type="xs:double" name="value" use="optional"/></xs:extension></xs:simpleContent></xs:complexType>
<xs:complexType name="bool"><xs:simpleContent><xs:extension base="xs:string">
  <xs:attribute type="xs:boolean" name="value" use="optional"/></xs:extension></xs:simpleContent></xs:complexType>
<xs:complexType name="string"><xs:simpleContent><xs:extension base="xs:string">
  <xs:attribute type="xs:string" name="value" use="optional"/></xs:extension></xs:simpleContent></xs:complexType>

<xs:complexType name="com.struqt.jdbc.config.JdbcRunnerConf">
  <xs:sequence>
    <xs:element name="moduleName" minOccurs="0" maxOccurs="2048" type="tns:string" />
    <xs:element name="defaultDataSource" minOccurs="0" maxOccurs="2048" type="tns:string" />
    <xs:element name="mapStatement" minOccurs="0" maxOccurs="2048" >
      <xs:complexType>
      <xs:sequence>
      <xs:element name="Statement" minOccurs="0" maxOccurs="2048" type="tns:com.struqt.jdbc.config.Statement" />
      </xs:sequence></xs:complexType>
    </xs:element>
    <xs:element name="mapDataSource" minOccurs="0" maxOccurs="2048" >
      <xs:complexType>
      <xs:sequence>
      <xs:element name="DataSourceConf" minOccurs="0" maxOccurs="2048" type="tns:com.struqt.jdbc.config.DataSourceConf" />
      </xs:sequence></xs:complexType>
    </xs:element>
  </xs:sequence>
  <xs:attribute name="moduleName" type="xs:string" />
  <xs:attribute name="defaultDataSource" type="xs:string" />
</xs:complexType>
<xs:complexType name="com.struqt.jdbc.config.Statement">
  <xs:sequence>
    <xs:element name="key" minOccurs="0" maxOccurs="2048" type="tns:string" />
    <xs:element name="dialect" minOccurs="0" maxOccurs="2048" type="tns:string" />
    <xs:element name="desc" minOccurs="0" maxOccurs="2048" type="tns:string" />
    <xs:element name="sql" minOccurs="0" maxOccurs="2048" type="tns:string" />
    <xs:element name="dataSource" minOccurs="0" maxOccurs="2048" type="tns:string" />
    <xs:element name="attributes" minOccurs="0" maxOccurs="2048" >
      <xs:complexType>
      <xs:sequence>
      <xs:element name="string" minOccurs="0" maxOccurs="2048" >
      <xs:complexType><xs:complexContent>
      <xs:extension base="tns:string">
      <xs:attribute name="key" type="xs:string" use="required" />
      </xs:extension></xs:complexContent></xs:complexType>
      </xs:element>
      </xs:sequence></xs:complexType>
    </xs:element>
  </xs:sequence>
  <xs:attribute name="key" type="xs:string" />
  <xs:attribute name="dialect" type="xs:string" />
  <xs:attribute name="desc" type="xs:string" />
  <xs:attribute name="sql" type="xs:string" />
  <xs:attribute name="dataSource" type="xs:string" />
</xs:complexType>
<xs:complexType name="com.struqt.jdbc.config.DataSourceConf">
  <xs:sequence>
    <xs:element name="key" minOccurs="0" maxOccurs="2048" type="tns:string" />
    <xs:element name="dialect" minOccurs="0" maxOccurs="2048" type="tns:string" />
    <xs:element name="jdbcUrl" minOccurs="0" maxOccurs="2048" type="tns:string" />
    <xs:element name="database" minOccurs="0" maxOccurs="2048" type="tns:string" />
    <xs:element name="username" minOccurs="0" maxOccurs="2048" type="tns:string" />
    <xs:element name="password" minOccurs="0" maxOccurs="2048" type="tns:string" />
    <xs:element name="provider" minOccurs="0" maxOccurs="2048" type="tns:string" />
    <xs:element name="properties" minOccurs="0" maxOccurs="2048" >
      <xs:complexType>
      <xs:sequence>
      <xs:element name="string" minOccurs="0" maxOccurs="2048" >
      <xs:complexType><xs:complexContent>
      <xs:extension base="tns:string">
      <xs:attribute name="key" type="xs:string" use="required" />
      </xs:extension></xs:complexContent></xs:complexType>
      </xs:element>
      </xs:sequence></xs:complexType>
    </xs:element>
    <xs:element name="attributes" minOccurs="0" maxOccurs="2048" >
      <xs:complexType>
      <xs:sequence>
      <xs:element name="string" minOccurs="0" maxOccurs="2048" >
      <xs:complexType><xs:complexContent>
      <xs:extension base="tns:string">
      <xs:attribute name="key" type="xs:string" use="required" />
      </xs:extension></xs:complexContent></xs:complexType>
      </xs:element>
      </xs:sequence></xs:complexType>
    </xs:element>
  </xs:sequence>
  <xs:attribute name="key" type="xs:string" />
  <xs:attribute name="dialect" type="xs:string" />
  <xs:attribute name="jdbcUrl" type="xs:string" />
  <xs:attribute name="database" type="xs:string" />
  <xs:attribute name="username" type="xs:string" />
  <xs:attribute name="password" type="xs:string" />
  <xs:attribute name="provider" type="xs:string" />
</xs:complexType>
</schema>

=== struqt/struqt-jdbc/struqt-jdbc-config/src/main/resources/invar/data/example.xml
<tns:root
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="invar.data data.xsd" xmlns:tns="invar.data">

  <moduleName value="test"/>
  <defaultDataSource value="default"/>

  <mapStatement>
    <Statement key="select-now-datetime" desc="Query current time of database">
      <sql><![CDATA[
        select now()
      ]]></sql>
    </Statement>
  </mapStatement>

  <mapDataSource>
    <DataSourceConf key="default" dialect="MySQL">
      <!-- https://github.com/brettwooldridge/HikariCP/wiki/Configuration -->
      <provider value="com.struqt.jdbc.HikariProvider"/>
      <jdbcUrl value="jdbc:mysql://127.0.0.1:33061/"/>
      <database><![CDATA[
        struqt_example?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8 ]]></database>
      <username value="root"/>
      <password value="123!@#4567"/>
      <properties>
        <string key="maximumPoolSize" value="150"/>
        <string key="minimumIdle" value="3"/>
        <string key="connectionTimeout" value="15000"/>
        <string key="idleTimeout" value="600000"/>
        <string key="maxLifetime" value="900000"/>
      </properties>
      <!-- https://github.com/brettwooldridge/HikariCP/wiki/MySQL-Configuration -->
      <attributes>
        <string key="rewriteBatchedStatements" value="true"/>
        <string key="useServerPrepStmts" value="true"/>
        <string key="cachePrepStmts" value="true"/>
        <string key="prepStmtCacheSize" value="350"/>
        <string key="prepStmtCacheSqlLimit" value="1024"/>
      </attributes>
    </DataSourceConf>
  </mapDataSource>

</tns:root>
